server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod

  application:
    name: gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761


logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web: WARN